// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContactType int32

const (
	ContactType_EMAIL      ContactType = 0
	ContactType_PHONE_TEXT ContactType = 1
	ContactType_PHONE_CALL ContactType = 2
)

var ContactType_name = map[int32]string{
	0: "EMAIL",
	1: "PHONE_TEXT",
	2: "PHONE_CALL",
}

var ContactType_value = map[string]int32{
	"EMAIL":      0,
	"PHONE_TEXT": 1,
	"PHONE_CALL": 2,
}

func (x ContactType) String() string {
	return proto.EnumName(ContactType_name, int32(x))
}

func (ContactType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

type HouseholdMember struct {
	GivenName            string               `protobuf:"bytes,1,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	Birthday             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HouseholdMember) Reset()         { *m = HouseholdMember{} }
func (m *HouseholdMember) String() string { return proto.CompactTextString(m) }
func (*HouseholdMember) ProtoMessage()    {}
func (*HouseholdMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *HouseholdMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HouseholdMember.Unmarshal(m, b)
}
func (m *HouseholdMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HouseholdMember.Marshal(b, m, deterministic)
}
func (m *HouseholdMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HouseholdMember.Merge(m, src)
}
func (m *HouseholdMember) XXX_Size() int {
	return xxx_messageInfo_HouseholdMember.Size(m)
}
func (m *HouseholdMember) XXX_DiscardUnknown() {
	xxx_messageInfo_HouseholdMember.DiscardUnknown(m)
}

var xxx_messageInfo_HouseholdMember proto.InternalMessageInfo

func (m *HouseholdMember) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *HouseholdMember) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

type Host struct {
	Capacity             uint32   `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Kids                 bool     `protobuf:"varint,3,opt,name=kids,proto3" json:"kids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetCapacity() uint32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Host) GetKids() bool {
	if m != nil {
		return m.Kids
	}
	return false
}

type Household struct {
	Id                   []byte               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Surname              string               `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Members              []*HouseholdMember   `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone                uint32               `protobuf:"varint,5,opt,name=phone,proto3" json:"phone,omitempty"`
	PreferredContact     ContactType          `protobuf:"varint,6,opt,name=preferred_contact,json=preferredContact,proto3,enum=models.ContactType" json:"preferred_contact,omitempty"`
	Active               bool                 `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	Host                 bool                 `protobuf:"varint,8,opt,name=host,proto3" json:"host,omitempty"`
	Added                *timestamp.Timestamp `protobuf:"bytes,9,opt,name=added,proto3" json:"added,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Household) Reset()         { *m = Household{} }
func (m *Household) String() string { return proto.CompactTextString(m) }
func (*Household) ProtoMessage()    {}
func (*Household) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{2}
}

func (m *Household) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Household.Unmarshal(m, b)
}
func (m *Household) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Household.Marshal(b, m, deterministic)
}
func (m *Household) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Household.Merge(m, src)
}
func (m *Household) XXX_Size() int {
	return xxx_messageInfo_Household.Size(m)
}
func (m *Household) XXX_DiscardUnknown() {
	xxx_messageInfo_Household.DiscardUnknown(m)
}

var xxx_messageInfo_Household proto.InternalMessageInfo

func (m *Household) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Household) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *Household) GetMembers() []*HouseholdMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Household) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Household) GetPhone() uint32 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *Household) GetPreferredContact() ContactType {
	if m != nil {
		return m.PreferredContact
	}
	return ContactType_EMAIL
}

func (m *Household) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Household) GetHost() bool {
	if m != nil {
		return m.Host
	}
	return false
}

func (m *Household) GetAdded() *timestamp.Timestamp {
	if m != nil {
		return m.Added
	}
	return nil
}

type Group struct {
	HostId               []byte               `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	HouseholdIds         [][]byte             `protobuf:"bytes,3,rep,name=household_ids,json=householdIds,proto3" json:"household_ids,omitempty"`
	DateAssigned         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date_assigned,json=dateAssigned,proto3" json:"date_assigned,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{3}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetHostId() []byte {
	if m != nil {
		return m.HostId
	}
	return nil
}

func (m *Group) GetHouseholdIds() [][]byte {
	if m != nil {
		return m.HouseholdIds
	}
	return nil
}

func (m *Group) GetDateAssigned() *timestamp.Timestamp {
	if m != nil {
		return m.DateAssigned
	}
	return nil
}

type Settings struct {
	DbPath               string   `protobuf:"bytes,1,opt,name=db_path,json=dbPath,proto3" json:"db_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Settings) Reset()         { *m = Settings{} }
func (m *Settings) String() string { return proto.CompactTextString(m) }
func (*Settings) ProtoMessage()    {}
func (*Settings) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{4}
}

func (m *Settings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Settings.Unmarshal(m, b)
}
func (m *Settings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Settings.Marshal(b, m, deterministic)
}
func (m *Settings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Settings.Merge(m, src)
}
func (m *Settings) XXX_Size() int {
	return xxx_messageInfo_Settings.Size(m)
}
func (m *Settings) XXX_DiscardUnknown() {
	xxx_messageInfo_Settings.DiscardUnknown(m)
}

var xxx_messageInfo_Settings proto.InternalMessageInfo

func (m *Settings) GetDbPath() string {
	if m != nil {
		return m.DbPath
	}
	return ""
}

func init() {
	proto.RegisterEnum("models.ContactType", ContactType_name, ContactType_value)
	proto.RegisterType((*HouseholdMember)(nil), "models.HouseholdMember")
	proto.RegisterType((*Host)(nil), "models.Host")
	proto.RegisterType((*Household)(nil), "models.Household")
	proto.RegisterType((*Group)(nil), "models.Group")
	proto.RegisterType((*Settings)(nil), "models.Settings")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573) }

var fileDescriptor_0b5431a010549573 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x51, 0x8b, 0xd3, 0x40,
	0x14, 0x85, 0x4d, 0xb6, 0x4d, 0xdb, 0xdb, 0xb4, 0xd6, 0x51, 0xdc, 0xa1, 0x20, 0x96, 0xee, 0x4b,
	0xf0, 0xa1, 0xab, 0x15, 0x16, 0xdf, 0xb4, 0x2c, 0xc5, 0x16, 0xba, 0xeb, 0x12, 0xfb, 0xe0, 0x5b,
	0x98, 0x74, 0xee, 0x26, 0x83, 0x4d, 0x26, 0x64, 0xa6, 0x0b, 0xfb, 0x07, 0xfc, 0x45, 0xfe, 0x40,
	0xc9, 0x4c, 0x12, 0xc5, 0x07, 0x7d, 0xcb, 0x39, 0x9c, 0xb9, 0xf7, 0xdc, 0x8f, 0x80, 0x9f, 0x49,
	0x8e, 0x47, 0xb5, 0x28, 0x4a, 0xa9, 0x25, 0xf1, 0xac, 0x9a, 0xbe, 0x4e, 0xa4, 0x4c, 0x8e, 0x78,
	0x69, 0xdc, 0xf8, 0x74, 0x7f, 0xa9, 0x45, 0x86, 0x4a, 0xb3, 0xac, 0xb0, 0xc1, 0x79, 0x0a, 0x4f,
	0x37, 0xf2, 0xa4, 0x30, 0x95, 0x47, 0x7e, 0x83, 0x59, 0x8c, 0x25, 0x79, 0x05, 0x90, 0x88, 0x07,
	0xcc, 0xa3, 0x9c, 0x65, 0x48, 0x9d, 0x99, 0x13, 0x0c, 0xc2, 0x81, 0x71, 0x6e, 0x59, 0x86, 0xe4,
	0x0a, 0xfa, 0xb1, 0x28, 0x75, 0xca, 0xd9, 0x23, 0x75, 0x67, 0x4e, 0x30, 0x5c, 0x4e, 0x17, 0x76,
	0xcb, 0xa2, 0xd9, 0xb2, 0xd8, 0x37, 0x5b, 0xc2, 0x36, 0x3b, 0xbf, 0x82, 0xce, 0x46, 0x2a, 0x4d,
	0xa6, 0xd0, 0x3f, 0xb0, 0x82, 0x1d, 0x84, 0xb6, 0xef, 0x47, 0x61, 0xab, 0x09, 0x81, 0xce, 0x77,
	0xc1, 0x15, 0x3d, 0x9b, 0x39, 0x41, 0x3f, 0x34, 0xdf, 0xf3, 0x9f, 0x2e, 0x0c, 0xda, 0x8a, 0x64,
	0x0c, 0xae, 0xe0, 0xa6, 0x94, 0x1f, 0xba, 0x82, 0x13, 0x0a, 0x3d, 0x75, 0x2a, 0x4d, 0x53, 0xd7,
	0x34, 0x6d, 0x24, 0x79, 0x07, 0xbd, 0xcc, 0x1c, 0x54, 0x8d, 0x3b, 0x0b, 0x86, 0xcb, 0xf3, 0x45,
	0x8d, 0xe8, 0xaf, 0x83, 0xc3, 0x26, 0x47, 0x5e, 0x40, 0x17, 0x33, 0x26, 0x8e, 0xb4, 0x63, 0x46,
	0x59, 0x51, 0xb9, 0x45, 0x2a, 0x73, 0xa4, 0x5d, 0xd3, 0xd6, 0x0a, 0xf2, 0x09, 0x9e, 0x15, 0x25,
	0xde, 0x63, 0x59, 0x22, 0x8f, 0x0e, 0x32, 0xd7, 0xec, 0xa0, 0xa9, 0x37, 0x73, 0x82, 0xf1, 0xf2,
	0x79, 0xb3, 0xe8, 0xda, 0xda, 0xfb, 0xc7, 0x02, 0xc3, 0x49, 0x9b, 0xae, 0x5d, 0xf2, 0x12, 0x3c,
	0x76, 0xd0, 0xe2, 0x01, 0x69, 0xcf, 0x9c, 0x5b, 0xab, 0x0a, 0x42, 0x2a, 0x95, 0xa6, 0x7d, 0x0b,
	0xa1, 0xfa, 0x26, 0x6f, 0xa1, 0xcb, 0x38, 0x47, 0x4e, 0x07, 0xff, 0x25, 0x6e, 0x83, 0xf3, 0x1f,
	0x0e, 0x74, 0x3f, 0x97, 0xf2, 0x54, 0x90, 0x73, 0xe8, 0x55, 0x33, 0x22, 0xc1, 0x0d, 0x22, 0x3f,
	0xf4, 0x2a, 0xb9, 0xe5, 0xe4, 0x02, 0x46, 0x69, 0x83, 0x22, 0xb2, 0xd8, 0xcf, 0x02, 0x3f, 0xf4,
	0x5b, 0x73, 0xcb, 0x15, 0xf9, 0x08, 0x23, 0xce, 0x34, 0x46, 0x4c, 0x29, 0x91, 0xe4, 0xc8, 0x0d,
	0x9b, 0x7f, 0x37, 0xf0, 0xab, 0x07, 0xab, 0x3a, 0x3f, 0xbf, 0x80, 0xfe, 0x57, 0xd4, 0x5a, 0xe4,
	0x89, 0xaa, 0xaa, 0xf0, 0x38, 0x2a, 0x98, 0x4e, 0xeb, 0xff, 0xca, 0xe3, 0xf1, 0x1d, 0xd3, 0xe9,
	0x9b, 0x0f, 0x30, 0xfc, 0x03, 0x16, 0x19, 0x40, 0x77, 0x7d, 0xb3, 0xda, 0xee, 0x26, 0x4f, 0xc8,
	0x18, 0xe0, 0x6e, 0xf3, 0xe5, 0x76, 0x1d, 0xed, 0xd7, 0xdf, 0xf6, 0x13, 0xe7, 0xb7, 0xbe, 0x5e,
	0xed, 0x76, 0x13, 0x37, 0xf6, 0x4c, 0x81, 0xf7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x86, 0x0f,
	0x96, 0x12, 0x00, 0x03, 0x00, 0x00,
}
